apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "file-server.fullname" . }}
  labels:
    {{- include "file-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "file-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "file-server.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ template "file-server.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.registryUrl }}/{{ .Chart.Name }}:{{ .Chart.AppVersion }}"
          ports:
             - name: http
               containerPort: 8090
               protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
            successThreshold: 1

